name: Label Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set labels based on title
        id: set-title-label
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"skill"* ]]; then
            echo "title_label=skill" >> $GITHUB_ENV
          elif [[ "${{ github.event.pull_request.title }}" == *"knowledge"* ]]; then
            echo "title_label=knowledge" >> $GITHUB_ENV
          fi

      - name: Check commit messages for labels
        id: check-commits
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          skill_commit=false
          knowledge_commit=false
          while read -r commit_message; do
            if [[ "$commit_message" == *"skill"* ]]; then
              skill_commit=true
            elif [[ "$commit_message" == *"knowledge"* ]]; then
              knowledge_commit=true
            fi
          done < <(git log origin/${{ github.event.pull_request.head.ref }} --pretty=format:%s)
          if [ "$skill_commit" = true ]; then
            echo "commit_label=skill" >> $GITHUB_ENV
          elif [ "$knowledge_commit" = true ]; then
            echo "commit_label=knowledge" >> $GITHUB_ENV
          fi

      - name: Apply labels
        uses: actions/github-script@v6
        if: env.title_label || env.commit_label
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = [];
            if (process.env.title_label) {
              labels.push(process.env.title_label);
            }
            if (process.env.commit_label) {
              labels.push(process.env.commit_label);
            }
            if (labels.length > 0) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labels
              });
            }
