name: Label Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commits and apply labels
        id: apply-labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const octokit = require('@actions/github').getOctokit(process.env.GITHUB_TOKEN);
            const context = require('@actions/github').context;
            const { data: commits } = await octokit.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            let skillCommit = false;
            let knowledgeCommit = false;

            commits.forEach(commit => {
              if (commit.commit.message.includes('skill')) {
                skillCommit = true;
              }
              if (commit.commit.message.includes('knowledge')) {
                knowledgeCommit = true;
              }
            });

            if (skillCommit) {
              await octokit.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['skill']
              });
            }

            if (knowledgeCommit) {
              await octokit.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['knowledge']
              });
            }
