name: Label Pull Requests with Skills and Knowledge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Labels from Title and Commits
        id: check_labels
        run: |
          LABELS=()

          # Check PR title for keywords
          echo "Checking PR title..."
          if echo "${{ github.event.pull_request.title }}" | grep -iq 'skill'; then
            LABELS+=("skill")
          fi
          if echo "${{ github.event.pull_request.title }}" | grep -iq 'knowledge'; then
            LABELS+=("knowledge")
          fi

          # Check last 10 commits for keywords
          echo "Checking commit messages..."
          git log --format=%B -n 10 ${GITHUB_SHA} | while read commit; do
            if echo "$commit" | grep -iq 'skill'; then
              LABELS+=("skill")
            elif echo "$commit" | grep -iq 'knowledge'; then
              LABELS+=("knowledge")
            fi
          done

          # Remove duplicates
          LABELS=($(echo "${LABELS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          LABEL_STRING="${LABELS[*]}"
          LABEL_STRING="${LABEL_STRING// /,}"
          echo "Labels to apply: $LABEL_STRING"
          echo "::set-output name=labels::$LABEL_STRING"

      - name: Apply labels
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/labeler.yml'
        env:
          LABELS: ${{ steps.check_labels.outputs.labels }}
