name: Assign Labels

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute assign labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'skill'
                nouns: ['skill', 'Skill']
                labels: ['skill']
              - type: 'knowledge'
                nouns: ['knowledge', 'Knowledge']
                labels: ['knowledge']
          maintain-labels-not-matched: false
          apply-changes: true
