name: Label Pull Requests with Skills and Knowledge

on:
  pull_request_target

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Determine Labels from Title and Commits
        id: check_labels
        run: |
          LABELS=()

          # Check PR title for keywords
          echo "Checking PR title..."
          if echo "${{ github.event.pull_request.title }}" | grep -iq 'skill'; then
            LABELS+=("skill")
          fi
          if echo "${{ github.event.pull_request.title }}" | grep -iq 'knowledge'; then
            LABELS+=("knowledge")
          fi

          # Check last 10 commits for keywords
          echo "Checking commit messages..."
          git log --format=%B -n 10 ${GITHUB_SHA} | while read commit; do
            if echo "$commit" | grep -iq 'skill'; then
              LABELS+=("skill")
            elif echo "$commit" | grep -iq 'knowledge'; then
              LABELS+=("knowledge")
            fi
          done

          # Remove duplicates
          LABELS=($(echo "${LABELS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          LABEL_STRING="${LABELS[*]}"
          LABEL_STRING="${LABEL_STRING// /,}"
          echo "Labels to apply: $LABEL_STRING"
          echo "::set-output name=labels::$LABEL_STRING"

  add-comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: "Add comment"
        run: |
          gh pr comment "${PULL_REQUEST_NUMBER}" --body "${PULL_REQUEST_COMMENT}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
          PULL_REQUEST_COMMENT: >
            Hi! So you've been marked as `triage-uncertain`, don't fret!
            This just means the triage team or member needs to discuss your PR during one of our [public meetings](https://github.com/instructlab/community/blob/main/Collaboration.md#triager-standup) before making a decision. (Yes! You are more than welcome to join us.)
            You have either made something amazing, or maybe hit a corner case that we hadn't thought of, or something like that.
            :star2: Thank you for your contribution! And you are pushing our :dog: :computer: project and we can't thank you enough. :sparkles:
