name: Label Pull Requests
on:
  pull_request:

jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Labels
        id: labeler
        run: |
          LABELS=()

          if echo "${{ github.event.pull_request.title }}" | grep -iq 'skill'; then
            LABELS+=("skill")
            echo "Skill label added from title"
          fi

          if echo "${{ github.event.pull_request.title }}" | grep -iq 'knowledge'; then
            LABELS+=("knowledge")
            echo "Knowledge label added from title"
          fi

          echo "Checking commit messages..."
          git log --format=%B -n 10 ${GITHUB_SHA} | while read commit; do
            echo "Commit message: $commit"
            if echo "$commit" | grep -iq 'skill'; then
              LABELS+=("skill")
              echo "Skill label added from commit"
            elif echo "$commit" | grep -iq 'knowledge'; then
              LABELS+=("knowledge")
              echo "Knowledge label added from commit"
            fi
          done

          LABELS=($(echo "${LABELS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          LABEL_STRING="${LABELS[*]}"
          LABEL_STRING="${LABEL_STRING// /,}"
          echo "Final label string: ${LABEL_STRING}"
          echo "::set-output name=label_string::${LABEL_STRING}"

      - name: Add Labels to Pull Request
        if: ${{ steps.labeler.outputs.label_string }}
        run: |
          echo "Adding labels to PR: ${{ steps.labeler.outputs.label_string }}"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ steps.labeler.outputs.label_string }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
