name: Label issues

on:
  pull_request:

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate and Add Labels to Issue
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh auth status
          gh issue edit "${{ github.event.issue.number }}" --add-label "triage"
